### ISSUE TITLE
IllegalStateException crashes

### ISSUE THREAD

**Issue by dkang-wow** [optimizely/Optimizely-Android-SDK#10]
Hi Optimizely,

I realised there are so many crashes from our live app as below.
It's a gradle project. Can you please check the issue as soon as possible?

com.optimizely.e.b$2.run
java.lang.IllegalStateException: Couldn't read row 0, col 0 from CursorWindow. Make sure the Cursor is initialized correctly before accessing data from it.

Exception Backtrace:
1   android.database.CursorWindow.nativeGetLong Native Method
2   android.database.CursorWindow.getLong   CursorWindow.java, line 524
3   android.database.AbstractWindowedCursor.getLong AbstractWindowedCursor.java, line 75
4   com.optimizely.e.b$2.run    SourceFile, line 208
5   com.optimizely.e.a.d    SourceFile, line 158
6   com.optimizely.e.a.handleMessage    SourceFile, line 139
7   android.os.Handler.dispatchMessage

**Comment by Daio-io** [comment]
Having the same problem. Here is a slightly more unobfusctaed version of the crash:

java.lang.IllegalStateException: Couldn't read row 0, col 0 from CursorWindow.  Make sure the Cursor is initialized correctly before accessing data from it.
    at android.database.CursorWindow.nativeGetLong(Native Method)
    at android.database.CursorWindow.getLong(CursorWindow.java:524)
    at android.database.AbstractWindowedCursor.getLong(AbstractWindowedCursor.java:75)
    at com.optimizely.LogAndEvent.OptimizelyDataStore$2.run(Unknown Source)
    at com.optimizely.LogAndEvent.DatabaseRunner.replayQueue(Unknown Source)
    at com.optimizely.LogAndEvent.DatabaseRunner.handleMessage(Unknown Source)
    at android.os.Handler.dispatchMessage(Handler.java:98)
    at android.os.Looper.loop(Looper.java:145)
    at com.optimizely.LogAndEvent.DatabaseRunner.run(Unknown Source)

**Comment by bsiver** [comment]
We started getting this recently too.  Any word on a possible resolution?

```
Fatal Exception: java.lang.IllegalStateException: Couldn't read row 0, col 0 from CursorWindow.  Make sure the Cursor is initialized correctly before accessing data from it.
       at android.database.CursorWindow.nativeGetLong(CursorWindow.java)
       at android.database.CursorWindow.getLong(CursorWindow.java:524)
       at android.database.AbstractWindowedCursor.getLong(AbstractWindowedCursor.java:75)
       at com.optimizely.LogAndEvent.OptimizelyDataStore.getPending(OptimizelyDataStore.java:169)
       at com.optimizely.LogAndEvent.OptimizelyDataStore.getPendingLogs(OptimizelyDataStore.java:144)
       at com.optimizely.LogAndEvent.OptimizelyLogManager.flushLogs(OptimizelyLogManager.java:67)
       at com.optimizely.IntentHandler.handleActionFlushLogs(IntentHandler.java:108)
       at com.optimizely.IntentHandler.handleIntent(IntentHandler.java:50)
       at com.optimizely.OptlyIoService.onHandleIntent(OptlyIoService.java:165)
       at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:66)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:158)
       at android.os.HandlerThread.run(HandlerThread.java:61)
```

**Comment by bsiver** [comment]
We discovered this issue occurs only after upgrading to version 1.6.0.  Reverting to 1.5.0 fixes the problem.

**Comment by tasomaniac** [comment]
Just an update. This crash still occurs with version 1.7
