### ISSUE TITLE
resource leak in OptimizelySDKVerifier

### ISSUE THREAD

**Issue by ber4444** [optimizely/Optimizely-Android-SDK#7]
```
02-25 14:18:47.485 9528-9537/com.wavemarket.waplauncher:Popup E/StrictMode: A resource was acquired at attached stack trace but never released. See java.io.Closeable for information on avoiding resource leaks.
                                                                            java.lang.Throwable: Explicit termination method 'close' not called
                                                                                at dalvik.system.CloseGuard.open(CloseGuard.java:184)
                                                                                at com.android.org.conscrypt.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:278)
                                                                                at com.squareup.okhttp.Connection.connectTls(Connection.java:239)
                                                                                at com.squareup.okhttp.Connection.connectSocket(Connection.java:201)
                                                                                at com.squareup.okhttp.Connection.connect(Connection.java:172)
                                                                                at com.squareup.okhttp.Connection.connectAndSetOwner(Connection.java:358)
                                                                                at com.squareup.okhttp.OkHttpClient$1.connectAndSetOwner(OkHttpClient.java:117)
                                                                                at com.squareup.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:329)
                                                                                at com.squareup.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:246)
                                                                                at com.squareup.okhttp.Call.getResponse(Call.java:276)
                                                                                at com.squareup.okhttp.Call$ApplicationInterceptorChain.proceed(Call.java:234)
                                                                                at com.squareup.okhttp.Call.getResponseWithInterceptorChain(Call.java:196)
                                                                                at com.squareup.okhttp.Call.execute(Call.java:79)
                                                                                at com.optimizely.utils.OptimizelySDKVerifier$SDKVerifierTask.doInBackground(OptimizelySDKVerifier.java:61)
                                                                                at com.optimizely.utils.OptimizelySDKVerifier$SDKVerifierTask.doInBackground(OptimizelySDKVerifier.java:39)
                                                                                at android.os.AsyncTask$2.call(AsyncTask.java:288)
                                                                                at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                                at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                                                at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                                                at java.lang.Thread.run(Thread.java:841)
02-25 14:18:47.485 9528-9537/com.wavemarket.waplauncher:Popup E/StrictMode: A resource was acquired at attached stack trace but never released. See java.io.Closeable for information on avoiding resource leaks.
                                                                            java.lang.Throwable: Explicit termination method 'end' not called
                                                                                at dalvik.system.CloseGuard.open(CloseGuard.java:184)
                                                                                at java.util.zip.Inflater.<init>(Inflater.java:82)
                                                                                at okio.GzipSource.<init>(GzipSource.java:62)
                                                                                at com.squareup.okhttp.internal.http.HttpEngine.unzip(HttpEngine.java:645)
                                                                                at com.squareup.okhttp.internal.http.HttpEngine.readResponse(HttpEngine.java:820)
                                                                                at com.squareup.okhttp.Call.getResponse(Call.java:277)
                                                                                at com.squareup.okhttp.Call$ApplicationInterceptorChain.proceed(Call.java:234)
                                                                                at com.squareup.okhttp.Call.getResponseWithInterceptorChain(Call.java:196)
                                                                                at com.squareup.okhttp.Call.execute(Call.java:79)
                                                                                at com.optimizely.utils.OptimizelySDKVerifier$SDKVerifierTask.doInBackground(OptimizelySDKVerifier.java:61)
                                                                                at com.optimizely.utils.OptimizelySDKVerifier$SDKVerifierTask.doInBackground(OptimizelySDKVerifier.java:39)
                                                                                at android.os.AsyncTask$2.call(AsyncTask.java:288)
                                                                                at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                                at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                                                at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                                                at java.lang.Thread.run(Thread.java:841)

```

**Comment by ber4444** [comment]
```
         try {
            OkHttpClient e = OptimizelySDKVerifier.optimizely.getHttpClient();
            RequestBody body = RequestBody.create(MediaType.parse("application/x-www-form-urlencoded"), String.format("project_id=%s&sdk_version=%s", new Object[]{projectId, sdkVersion}));
            Request request = (new Builder()).url("https://app.optimizely.com/mobile/installed").post(body).build();
            e.newCall(request).execute();
         } catch (Exception var7) {
            Log.e("OPTIMIZELY_SDK_VERIFIER", String.format("Failed to send SDK installation ping to Optimizely %s", new Object[]{projectId}), var7);
         }
```

You should close the body in a `finally` block.
